---

- name: "Setup | users | ensure group {{ group }} exists"
  ansible.builtin.group:
    name: "{{ kodi_group }}"
    state: present

- name: " Setup | users | ensure user {{ user }} exists"
  ansible.builtin.user:
    name: "{{ kodi_user }}"
    state: present
    group: "{{ kodi_group }}"
    groups: "{{ kodi_extra_groups }}"
  register: user_register

- name: " Setup | apt | ensure added repository"
  apt_repository: repo={{ kodi_pkg_apt_repo }}
  when: kodi_pkg_apt_repo != None

- name: " Setup | apt | ensure added base packages"
  apt: name={{ item }} update_cache=yes cache_valid_time=86400
  with_items:
    - software-properties-common
    - "kodi={{ kodi_pkg_apt_ver }}*"

- name: "Config | all | ensure created conf folders"
  file: >
    path={{ item }}
    state=directory
    owner={{ kodi_user }}
    mode=0755
  with_items:
    - "{{ user_register.home }}/{{ kodi_conf_dir }}"
    - "{{ user_register.home }}/{{ kodi_conf_dir }}/userdata"